import type { Metadata } from "next";
import { roboto } from "@/fonts/fonts";
import "../(root)/globals.css";
import Navbar from "@/components/Navbar/Navbar";
export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        <div>{children}</div>
      </body>
    </html>
  );
}
